# Alan Hurtarte
## 19000590

---

## Entramiento perceptron

---

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('data.csv')
data.describe()

x1          x2       label
count  200.000000  200.000000  200.000000
mean     9.031500    8.216340    0.500000
std      3.924414    1.577048    0.501255
min      3.079348    4.476515    0.000000
25%      5.297457    6.988940    0.000000
50%      8.802883    8.215413    0.500000
75%     12.818698    9.521257    1.000000
max     15.587962   11.625328    1.000000

In [6]:
data.head()

x1         x2  label
0  12.882292  10.228199      1
1  12.682271   9.360462      1
2  12.104981  10.580729      1
3  12.473947  10.993459      1
4  11.997386   9.321291      1

In [117]:
def predict_array(x, w):
    totals = np.zeros(x.shape[0])
    for i in range(len(x)):
        total = np.dot(x[i], w[1:]) + w[0]
        totals[i] = 1. if total > 0 else 0.
    return totals

def predict(x, w):
    total = np.dot(x, w[1:]) + w[0]
    return 1. if total > 0 else 0.

def train(xs, w, labels, epochs, learning_rate):
    for i in range(epochs):
        for x, label in zip(xs, labels):
            prediction = predict(x, w)
            w[1:] += learning_rate * (label - prediction) * x
            w[0] += learning_rate * (label - prediction)
            
    return w

### Testing with and gate

In [94]:
xs = []
xs.append(np.array([1, 1]))
xs.append(np.array([1, 0]))
xs.append(np.array([0, 1]))
xs.append(np.array([0, 0]))
labels = np.array([1., 0., 0., 0.])
w = np.zeros(3)
w = train(xs, w, labels, 100, 0.01)
w

array([-0.02,  0.01,  0.02])

In [95]:
inputs = np.array([1, 1])
print(predict(inputs, w) )
inputs = np.array([0, 1])
print(predict(inputs,  w) )

1.0
0.0


### Using dataset

In [104]:
from sklearn.model_selection import train_test_split
w = np.zeros(3)
epochs = 100
lr = 0.1
x = np.array([data['x1'], data['x2']])
x = x.transpose()
labels = data['label']
X_train, X_test, y_train, y_test = train_test_split(x, labels, test_size=0.33, random_state=42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(134, 2)
(134,)
(66, 2)
(66,)


In [105]:
w = train(X_train, w, y_train, 100, 0.01)
w

array([-2.06      ,  0.48948247, -0.39191846])

In [118]:
labels_predict = predict_array(X_test, w)
labels_predict

array([0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.])

In [122]:
error = np.mean( y_test != labels_predict )
error

0.09090909090909091